name: acceptance_tests
description: Dart SDK Acceptance testing framework
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  glob: ^2.0.1
  http: ^0.13.1
  archive: ^3.1.2
  dotenv: ^3.0.0-nullsafety.0
  gherkin: ^2.0.0
  test: ^1.15.0
  pubnub:
    path: ../pubnub
