---
changelog:
  -
    changes:
      -
        text: "Add ability to fetch current PubNub timetoken."
        type: feature
      -
        text: "Add ability to publish messages and signals to channels and channel groups."
        type: feature
      -
        text: "Add ability to subscribe to channels and channel groups."
        type: feature
      -
        text: "Add ability to manage Objects (Spaces, Users and Memberships)."
        type: feature
      -
        text: "Add ability to manage PubNub Access Manager."
        type: feature
      -
        text: "Add ability to manage device registration for Push Notification Service."
        type: feature
      -
        text: "Add ability to add, delete and retrieve message actions."
        type: feature
      -
        text: "Add channel and channel group abstractions to allow using History."
        type: feature
    date: Apr 15, 20
    version: v1.0.0
features:
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
    - ACCESS-GRANT-TOKEN
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-DELETE-MESSAGES
    - STORAGE-FETCH-MESSAGES
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-GET-USER
    - OBJECTS-GET-USERS
    - OBJECTS-CREATE-USER
    - OBJECTS-UPDATE-USER
    - OBJECTS-DELETE-USER
    - OBJECTS-GET-SPACE
    - OBJECTS-GET-SPACES
    - OBJECTS-CREATE-SPACE
    - OBJECTS-UPDATE-SPACE
    - OBJECTS-DELETE-SPACE
    - OBJECTS-GET-MEMBERSHIPS
    - OBJECTS-JOIN-SPACES
    - OBJECTS-UPDATE-MEMBERSHIPS
    - OBJECTS-LEAVE-SPACES
    - OBJECTS-GET-MEMBERS
    - OBJECTS-ADD-MEMBERS
    - OBJECTS-UPDATE-MEMBERS
    - OBJECTS-REMOVE-MEMBERS
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE
  time:
    - TIME-TIME
  token-management:
    - TOKEN-PARSE-TOKEN
    - TOKEN-SET-TOKEN
    - TOKEN-SET-TOKENS
    - TOKEN-GET-TOKEN
    - TOKEN-GET-TOKENS
    - TOKEN-CLEAR-TOKENS
name: dart
schema: 1
scm: github.com/pubnub/dart
supported-platforms:
  -
    frameworks:
      - "Flutter"
    platforms:
      - "Dart SDK >=2.6.0 <3.0.0"
version: "1.0.0"
