---
changelog:
  -
    changes:
      -
        text: "Fixes issue of exception from server when publishKey os null with publish call."
        type: bug
      -
        text: "Fixes missing url component in file publish message for sendFile and support for message encryption."
        type: bug
    date: Aug 5, 20
    version: v1.4.3
  -
    changes:
      -
        text: "Fixes issue of invalid type argument for fcm push gateway type."
        type: bug
    date: Jul 27, 20
    version: v1.4.2
  -
    changes:
      -
        text: "Fixes issue of missing exposed MessageType enum."
        type: bug
    date: Jul 24, 20
    version: v1.4.1
  -
    changes:
      -
        text: "Add file apis to support file feature."
        type: feature
      -
        text: "Add support for random initialization vector for messages and file."
        type: improvement
    date: Jul 23, 20
    version: v1.4.0
  -
    changes:
      -
        text: "Add message encryption support."
        type: feature
    date: Jun 25, 20
    version: v1.3.0
  -
    changes:
      -
        text: "Add simplified Objects API support with UUID and Channel metadata / membership management."
        type: feature
      -
        text: "Fixes missing PushGateway type support of fcm for Push Notification."
        type: bug
    date: Jun 10, 20
    version: v1.2.0
  -
    changes:
      -
        text: "Fixes unsubscribeAll so its no longer modifying subscription list during iteration."
        type: bug
      -
        text: "Fixes exports to include presence and channel group results."
        type: bug
    date: May 11, 20
    version: v1.1.3
  -
    changes:
      -
        text: "Fixes issues of missing types for objects and push-notification."
        type: bug
    date: May 6, 20
    version: v1.1.2
  -
    changes:
      -
        text: "Expose missing types."
        type: bug
    date: May 6, 20
    version: v1.1.1
  -
    changes:
      -
        text: "Refactors logging to rely on Zones."
        type: bug
      -
        text: "Fixes issues with resubscribing and improves injectLogger."
        type: bug
    date: May 5, 20
    version: v1.1.0
  -
    changes:
      -
        text: "Fix wrong API Uri in Push Notifications."
        type: bug
      -
        text: "Fix Subscription.unsubscribe to correctly close the messages stream."
        type: bug
    date: May 4, 20
    version: v1.0.5
  -
    changes:
      -
        text: "Add HereNow to PresenceDx, usable as `pubnub.hereNow()`."
        type: feature
      -
        text: "Fix subscribe `withPresence: true` not properly forwarding messages when used with wildcard channels."
        type: bug
    date: Apr 27, 20
    version: v1.0.4
  -
    changes:
      -
        text: "Change all Symbols to Strings to support Flutter better, fix a typo in SubscribeParams preventing subscribe from working."
        type: bug
    date: Apr 22, 20
    version: v1.0.3
  -
    changes:
      -
        text: "Add backward synchronization to private repository for `pubspec.yaml` and `lib/src/core/core.dart`."
        type: improvement
      -
        text: "Prevent tests from breaking when version is bumped."
        type: improvement
    date: Apr 18, 20
    version: v1.0.2
  -
    changes:
      -
        text: "Refactor PAM, hide logger instances and clean up tests."
        type: improvement
      -
        text: "Add `package:pedantic` config to analysis, fix lint issues."
        type: improvement
      -
        text: "Ensure()isEqual now uses correct template."
        type: bug
      -
        text: "Add PAM to library exports."
        type: bug
      -
        text: "Consistently use PubNubversion in tests."
        type: bug
    date: Apr 18, 20
    version: v1.0.1
  -
    changes:
      -
        text: "Add ability to fetch current PubNub timetoken."
        type: feature
      -
        text: "Add ability to publish messages and signals to channels and channel groups."
        type: feature
      -
        text: "Add ability to subscribe to channels and channel groups."
        type: feature
      -
        text: "Add ability to manage Objects (Spaces, Users and Memberships)."
        type: feature
      -
        text: "Add ability to manage PubNub Access Manager."
        type: feature
      -
        text: "Add ability to manage device registration for Push Notification Service."
        type: feature
      -
        text: "Add ability to add, delete and retrieve message actions."
        type: feature
      -
        text: "Add channel and channel group abstractions to allow using History."
        type: feature
    date: Apr 15, 20
    version: v1.0.0
features:
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
    - ACCESS-GRANT-TOKEN
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
    - PUBLISH-FILE-MESSAGE
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-DELETE-MESSAGES
    - STORAGE-FETCH-MESSAGES
    - STORAGE-MESSAGE-COUNT
    - STORAGE-HISTORY-WITH-META
    - STORAGE-FETCH-WITH-META
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
  signal:
    - SIGNAL-SEND
  objects:
    - OBJECTS-GET-ALL-UUID-METADATA
    - OBJECTS-GET-UUID-METADATA
    - OBJECTS-SET-UUID-METADATA
    - OBJECTS-REMOVE-UUID-METADATA
    - OBJECTS-GET-ALL-CHANNEL-METADATA
    - OBJECTS-GET-CHANNEL-METADATA
    - OBJECTS-SET-CHANNEL-METADATA
    - OBJECTS-REMOVE-CHANNEL-METADATA
    - OBJECTS-GET-MEMBERSHIPS-V2
    - OBJECTS-SET-MEMBERSHIPS-V2
    - OBJECTS-REMOVE-MEMBERSHIPS-V2
    - OBJECTS-GET-CHANNEL-MEMBERS-V2
    - OBJECTS-SET-CHANNEL-MEMBERS-V2
    - OBJECTS-REMOVE-CHANNEL-MEMBERS-V2
    - OBJECTS-MANAGE-MEMBERSHIPS-V2
    - OBJECTS-MANAGE-CHANNEL-MEMBERS-V2
    - OBJECTS-FILTERING
    - OBJECTS-SORTING
  files:
    - FILES-SEND-FILE
    - FILES-LIST-FILES
    - FILES-GET-FILE-URL
    - FILES-DELETE-FILE
    - FILES-DOWNLOAD-FILE
  message-actions:
    - MESSAGE-ACTIONS-GET
    - MESSAGE-ACTIONS-ADD
    - MESSAGE-ACTIONS-REMOVE
  time:
    - TIME-TIME
  others:
    - RANDOM-INITIALIZATION-VECTOR

name: dart
schema: 1
scm: github.com/pubnub/dart
supported-platforms:
  -
    frameworks:
      - "Flutter"
    platforms:
      - "Dart SDK >=2.6.0 <3.0.0"
    version: "PubNub Dart SDK"
version: "1.4.3"
