name: pubnub
description: PubNub SDK for Dart lang (with Flutter support)
version: 1.0.0
homepage: https://pubnub.com

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  pool: ^1.4.0
  dio: ^3.0.0
  meta: ^1.1.0
  uuid: ^2.0.0
  logging: ^0.11.0
  collection: ^1.14.0
  async: ^2.4.0
  crypto: ^2.1.4
  cbor: ^2.1.0
dev_dependencies:
  build_runner: 1.7.4
  json_serializable: 3.2.5
  test: 1.11.1
  test_coverage: 0.4.1
