name: pubnub
description: PubNub SDK v5 for Dart lang (with Flutter support) that allows you to create real-time applications
version: 3.2.0
homepage: https://www.pubnub.com/docs

environment:
  sdk: ">=2.8.0 <3.0.0"

scripts:
  test:
    default: pub run test -P unit
    integration: pub run test -P integration
  validate:
    analysis: dartanalyzer --fatal-warnings lib
    formatting: dartfmt -n --set-exit-if-changed lib

dependencies:
  async: ^2.4.2
  cbor: ^3.2.0
  convert: ^2.1.1
  crypto: ^2.1.5
  encrypt: ^4.0.0
  form_data: ^0.0.1
  meta: ^1.2.4
  pedantic: ^1.9.2
  pool: ^1.4.0
  xml: ^4.5.1
dev_dependencies:
  gherkin: 1.1.9
  test: 1.15.7
